export { BtnContainer } from "./btn-container/BtnContainer";
export { Error } from "./error/Error";
export { MainContent } from "./main-content/MainContent";
export { ProgressBar } from "./progress-bar/ProgressBar";
export { QuestionBox } from "./question-box/QuestionBox";
export { QuestionBoxHeading } from "./question-box-heading/QuestionBoxHeading";
export { QuestionBoxPara } from "./question-box-para/QuestionBoxPara";
export { QuestionInputIndustries } from "./question-input-industries/QuestionInputIndustries";
export { QuestionInputText } from "./question-input-text/QuestionInputText";
export { QuestionNumHeading } from "./question-num-heading/QuestionNumHeading";
export * from "./questions";
